"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Bell, BookOpen, ChevronRight, CircleHelp, ClipboardList, FileBarChart, Gauge, Laptop, Moon, Package, Plus, Search, Settings, ShieldCheck, Sun, TicketCheck, UserRound, Users, Wrench } from "lucide-react";
import { Toaster, toast } from "sonner";
import { assets, knowledge, people, tickets as initialTickets } from "@/data/mock";
import { parseRoute, routePath, type Page, type Route } from "@/lib/navigation";
import type { NewTicketInput, Priority, Ticket, TicketEvent, TicketMessage, TicketStatus } from "@/types";
import { slaHours, slaState, transitionSla } from "@/lib/service-desk";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuBadge, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AssetsPage, AssetDetail } from "@/features/assets/components";
import { Dashboard, InventoryPage, KnowledgePage, ReportsPage, SoftwarePage, UsersPage } from "@/features/portal/pages";
import { EmptyState } from "@/features/portal/shared";
import { CreateTicket, TicketDetail, TicketsPage, type TicketPreset } from "@/features/tickets/components";

const nav = [
  { label: "Overview", items: [{ page: "dashboard" as Page, label: "Dashboard", icon: Gauge }] },
  { label: "Service Desk", items: [{ page: "tickets" as Page, label: "My Tickets", icon: TicketCheck, preset: "mine" as TicketPreset }, { page: "tickets" as Page, label: "All Tickets", icon: ClipboardList, preset: "all" as TicketPreset }, { page: "tickets" as Page, label: "SLA Risk", icon: AlertTriangle, preset: "sla" as TicketPreset }] },
  { label: "Asset Management", items: [{ page: "assets" as Page, label: "Assets", icon: Laptop }, { page: "inventory" as Page, label: "Inventory", icon: Package }, { page: "software" as Page, label: "Software & Licenses", icon: ShieldCheck }] },
  { label: "Organization", items: [{ page: "users" as Page, label: "Users", icon: Users }, { page: "knowledge" as Page, label: "Knowledge Base", icon: BookOpen }, { page: "reports" as Page, label: "Reports", icon: FileBarChart }] },
];

function nowLabel() { return new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", timeZone: "Asia/Bangkok" }).format(new Date()); }
function starterEvents(ticket: Ticket): TicketEvent[] { return [{ id: `${ticket.id}-created`, time: ticket.created, label: "Ticket created" }, ...(ticket.assignee === "Unassigned" ? [] : [{ id: `${ticket.id}-assigned`, time: "09:45", label: `Assigned to ${ticket.assignee}` }]), ...(ticket.status === "New" ? [] : [{ id: `${ticket.id}-status`, time: "09:47", label: `Status changed to ${ticket.status}` }])]; }

// Frontend-only session state: no database, API, authentication backend, or persistence.
export default function Portal({ initialPath }: { initialPath: string }) {
  const [route, setRoute] = useState<Route>(() => parseRoute(initialPath));
  const [records, setRecords] = useState<Ticket[]>(() => [...initialTickets]);
  const [messages, setMessages] = useState<Record<string, TicketMessage[]>>({});
  const [events, setEvents] = useState<Record<string, TicketEvent[]>>({});
  const [ticketPreset, setTicketPreset] = useState<TicketPreset>("all");
  const [searchOpen, setSearchOpen] = useState(false);
  const [notificationsOpen, setNotificationsOpen] = useState(false);
  const [notificationsRead, setNotificationsRead] = useState(false);
  const [createOpen, setCreateOpen] = useState(false);
  const [seedAssetId, setSeedAssetId] = useState<string>();
  const [dark, setDark] = useState(false);

  const navigate = useCallback((next: Route) => { setRoute(next); const path = routePath(next); if (window.location.pathname !== path) window.history.pushState({}, "", path); window.scrollTo({ top: 0, behavior: "instant" }); }, []);
  useEffect(() => { const pop = () => setRoute(parseRoute(window.location.pathname)); window.addEventListener("popstate", pop); return () => window.removeEventListener("popstate", pop); }, []);
  useEffect(() => { const key = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setSearchOpen(true); } }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, []);
  useEffect(() => { const stored = window.localStorage.getItem("orbit-theme"); if (stored === "dark") setDark(true); }, []);
  useEffect(() => { document.documentElement.classList.toggle("dark", dark); window.localStorage.setItem("orbit-theme", dark ? "dark" : "light"); }, [dark]);
  useEffect(() => { const context = (document as Document & { modelContext?: { registerTool: (tool: unknown) => void } }).modelContext; try { context?.registerTool({ name: "start_ticket_creation", title: "Start ticket creation", description: "Open the visible ticket creation flow.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: false }, execute: () => { setCreateOpen(true); return { status: "opened" }; } }); } catch { /* Optional browser capability. */ } }, []);

  const selectedTicket = route.page === "ticket" ? records.find(ticket => ticket.id === route.id) : undefined;
  const selectedAsset = route.page === "asset" ? assets.find(asset => asset.id === route.id) : undefined;
  const ticketMessages = useMemo(() => selectedTicket ? [{ id: `${selectedTicket.id}-request`, author: selectedTicket.requester, role: "Requester" as const, body: selectedTicket.description, time: selectedTicket.created, visibility: "public" as const }, ...(messages[selectedTicket.id] ?? [])] : [], [selectedTicket, messages]);
  const ticketEvents = selectedTicket ? [...starterEvents(initialTickets.find(ticket => ticket.id === selectedTicket.id) ?? { ...selectedTicket, status: "New", assignee: "Unassigned" }), ...(events[selectedTicket.id] ?? [])] : [];
  const openTicket = (ticket: Ticket) => navigate({ page: "ticket", id: ticket.id });
  const openAsset = (id: string) => navigate({ page: "asset", id });
  const addEvent = (id: string, label: string) => setEvents(current => ({ ...current, [id]: [...(current[id] ?? []), { id: `${id}-${Date.now()}-${Math.random()}`, time: nowLabel(), label }] }));
  const updateTicket = (id: string, patch: Partial<Ticket>, event?: string) => { setRecords(current => current.map(ticket => ticket.id === id ? { ...ticket, ...patch, updated: "Just now" } : ticket)); if (event) addEvent(id, event); };
  const changeStatus = (ticket: Ticket, status: TicketStatus) => { if (status === ticket.status) return; if (status === "Assigned" && ticket.assignee === "Unassigned") { toast.error("Assign a technician before using Assigned status"); return; } updateTicket(ticket.id, { status, sla: transitionSla(ticket, status) }, `Status changed to ${status}`); toast.success(`Status changed to ${status}`); };
  const changePriority = (ticket: Ticket, priority: Priority) => { if (priority === ticket.priority) return; updateTicket(ticket.id, { priority, sla: transitionSla(ticket, ticket.status, priority) }, `Priority changed to ${priority} · ${slaHours[priority]}h SLA target`); toast.success(`Priority changed to ${priority}`); };
  const changeAssignee = (ticket: Ticket, assignee: string) => { if (assignee === ticket.assignee) return; const autoAssign = ticket.status === "New" && assignee !== "Unassigned"; updateTicket(ticket.id, { assignee, ...(autoAssign ? { status: "Assigned" as TicketStatus } : {}) }, `Assigned to ${assignee}${autoAssign ? " · status changed to Assigned" : ""}`); toast.success(`Assigned to ${assignee}`); };
  const sendMessage = (body: string, visibility: "public" | "internal") => { if (!selectedTicket) return; const message: TicketMessage = { id: `${selectedTicket.id}-${Date.now()}`, author: "Nattapon Wongchai", role: "IT Support", body, time: nowLabel(), visibility }; setMessages(current => ({ ...current, [selectedTicket.id]: [...(current[selectedTicket.id] ?? []), message] })); updateTicket(selectedTicket.id, {}, visibility === "public" ? "Reply sent to requester" : "Internal note added"); };
  const createTicket = (input: NewTicketInput) => { const nextNumber = Math.max(...records.map(ticket => Number(ticket.id.match(/\d+$/)?.[0] ?? 0))) + 1; const id = `INC-2026-${String(nextNumber).padStart(5, "0")}`; const ticket: Ticket = { id, title: input.title, description: input.description, requester: "Somchai Jaidee", department: "Accounting", category: input.category, priority: "P3 Medium", status: "New", assignee: "Unassigned", sla: "08:00", created: "Just now", updated: "Just now", asset: input.assetId === "none" ? undefined : input.assetId, location: input.location, attachments: input.attachments }; setRecords(current => [ticket, ...current]); toast.success(`${id} added to Tickets`); return id; };
  const openTickets = (preset: TicketPreset = "all") => { setTicketPreset(preset); navigate({ page: "tickets" }); };
  const startAssetTicket = (id: string) => { setSeedAssetId(id); setCreateOpen(true); };

  const riskTickets = records.filter(ticket => slaState(ticket).risk);
  const breadcrumbs = route.page === "dashboard" ? ["Overview", "Dashboard"] : route.page === "ticket" ? ["Tickets", route.id] : route.page === "asset" ? ["Assets", route.id] : [route.page[0].toUpperCase() + route.page.slice(1)];
  return <SidebarProvider><Sidebar collapsible="icon" className="border-r border-sidebar-border"><SidebarHeader className="h-16 justify-center border-b border-sidebar-border px-3"><button onClick={() => navigate({ page: "dashboard" })} className="flex items-center gap-2 overflow-hidden px-1 text-left"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-primary text-primary-foreground"><Wrench className="size-4" /></span><span className="leading-tight group-data-[collapsible=icon]:hidden"><strong className="block font-semibold">Orbit IT</strong><small className="text-muted-foreground">Service Operations</small></span></button></SidebarHeader><SidebarContent className="px-2 py-3">{nav.map(group => <SidebarGroup key={group.label}><SidebarGroupLabel>{group.label}</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{group.items.map(item => <SidebarMenuItem key={item.label}><SidebarMenuButton tooltip={item.label} isActive={route.page === item.page && (item.page !== "tickets" || ticketPreset === ("preset" in item ? item.preset : "all"))} onClick={() => item.page === "tickets" ? openTickets("preset" in item ? item.preset : "all") : navigate({ page: item.page })}><item.icon /><span>{item.label}</span></SidebarMenuButton>{item.label === "All Tickets" && <SidebarMenuBadge>{records.length}</SidebarMenuBadge>}{item.label === "SLA Risk" && <SidebarMenuBadge>{riskTickets.length}</SidebarMenuBadge>}</SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup>)}</SidebarContent><SidebarFooter className="border-t border-sidebar-border p-2"><SidebarMenu><SidebarMenuItem><SidebarMenuButton tooltip="Settings" onClick={() => toast.info("Settings are planned for a later phase")}><Settings /><span>Settings</span></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton tooltip="Help" onClick={() => navigate({ page: "knowledge" })}><CircleHelp /><span>Help & Support</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu><div className="flex items-center gap-2 p-2"><Avatar className="size-8"><AvatarFallback>NW</AvatarFallback></Avatar><div className="min-w-0 group-data-[collapsible=icon]:hidden"><p className="truncate text-sm font-medium">Nattapon Wongchai</p><p className="text-xs text-muted-foreground">IT Support</p></div></div></SidebarFooter></Sidebar>
    <SidebarInset className="min-w-0"><header className="sticky top-0 z-20 flex h-16 items-center gap-2 border-b bg-background/95 px-3 backdrop-blur md:px-6"><SidebarTrigger /><div className="hidden items-center gap-2 text-sm text-muted-foreground sm:flex">{breadcrumbs.map((crumb, index) => <span key={`${crumb}-${index}`} className="flex items-center gap-2">{index > 0 && <ChevronRight className="size-3.5" />}<span className={index === breadcrumbs.length - 1 ? "text-foreground" : ""}>{crumb}</span></span>)}</div><div className="ml-auto flex items-center gap-1.5"><Button variant="outline" onClick={() => setSearchOpen(true)} className="hidden w-72 justify-start font-normal text-muted-foreground lg:flex"><Search className="size-4" />Search tickets, assets, users…<kbd className="ml-auto rounded border px-1.5 text-[10px]">Ctrl K</kbd></Button><Button variant="ghost" size="icon" onClick={() => setSearchOpen(true)} className="lg:hidden" aria-label="Search"><Search className="size-4" /></Button><Button variant="ghost" size="icon" onClick={() => setDark(value => !value)} aria-label="Toggle theme">{dark ? <Sun className="size-4" /> : <Moon className="size-4" />}</Button><Button variant="ghost" size="icon" onClick={() => setNotificationsOpen(true)} aria-label="Notifications" className="relative"><Bell className="size-4" />{!notificationsRead && <span className="absolute right-2 top-2 size-1.5 rounded-full bg-red-500" />}</Button><DropdownMenu><DropdownMenuTrigger asChild><Button><Plus className="size-4" />Create</Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => { setSeedAssetId(undefined); setCreateOpen(true); }}><TicketCheck />New Ticket</DropdownMenuItem><DropdownMenuItem onClick={() => navigate({ page: "assets" })}><Laptop />New Asset</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem onClick={() => navigate({ page: "users" })}><UserRound />New User</DropdownMenuItem><DropdownMenuItem onClick={() => navigate({ page: "inventory" })}><Package />Inventory Item</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header>
      <main className="mx-auto w-full max-w-[1600px] p-4 pb-24 md:p-6 xl:p-8">
        {route.page === "dashboard" && <Dashboard tickets={records} onTicket={openTicket} onCreate={() => { setSeedAssetId(undefined); setCreateOpen(true); }} onAllTickets={() => openTickets("all")} />}
        {route.page === "tickets" && <TicketsPage tickets={records} preset={ticketPreset} onOpen={openTicket} onCreate={() => { setSeedAssetId(undefined); setCreateOpen(true); }} />}
        {route.page === "ticket" && (selectedTicket ? <TicketDetail ticket={selectedTicket} messages={ticketMessages} events={ticketEvents} onBack={() => openTickets("all")} onAsset={openAsset} onStatus={status => changeStatus(selectedTicket, status)} onPriority={priority => changePriority(selectedTicket, priority)} onAssign={name => changeAssignee(selectedTicket, name)} onEscalate={() => changePriority(selectedTicket, "P1 Critical")} onMessage={sendMessage} /> : <EmptyState title="Ticket not found" description="This ticket is not in the current sample data." onClear={() => openTickets("all")} />)}
        {route.page === "assets" && <AssetsPage assets={assets} onOpen={asset => openAsset(asset.id)} />}
        {route.page === "asset" && (selectedAsset ? <AssetDetail asset={selectedAsset} tickets={records} onBack={() => navigate({ page: "assets" })} onReport={startAssetTicket} onTicket={openTicket} /> : <EmptyState title="Asset not found" description="This asset is not in the current sample data." onClear={() => navigate({ page: "assets" })} />)}
        {route.page === "inventory" && <InventoryPage />}{route.page === "software" && <SoftwarePage />}{route.page === "users" && <UsersPage />}{route.page === "knowledge" && <KnowledgePage />}{route.page === "reports" && <ReportsPage />}
      </main>
    </SidebarInset>
    <CommandDialog open={searchOpen} onOpenChange={setSearchOpen} title="Global Search" description="Search tickets, assets, users and knowledge"><CommandInput placeholder="Search tickets, assets, users, knowledge…" /><CommandList><CommandEmpty>No results found.</CommandEmpty><CommandGroup heading="Tickets">{records.map(ticket => <CommandItem key={ticket.id} value={`${ticket.id} ${ticket.title} ${ticket.requester}`} onSelect={() => { openTicket(ticket); setSearchOpen(false); }}><TicketCheck className="size-4" /><span>{ticket.id} · {ticket.title}</span></CommandItem>)}</CommandGroup><CommandGroup heading="Assets">{assets.map(asset => <CommandItem key={asset.id} value={`${asset.id} ${asset.name} ${asset.user}`} onSelect={() => { openAsset(asset.id); setSearchOpen(false); }}><Laptop className="size-4" /><span>{asset.id} · {asset.name}</span></CommandItem>)}</CommandGroup><CommandGroup heading="Users">{people.map(person => <CommandItem key={person.id} value={`${person.name} ${person.department}`} onSelect={() => { navigate({ page: "users" }); setSearchOpen(false); }}><Users className="size-4" /><span>{person.name} · {person.department}</span></CommandItem>)}</CommandGroup><CommandGroup heading="Knowledge">{knowledge.map(article => <CommandItem key={article.title} value={`${article.title} ${article.category}`} onSelect={() => { navigate({ page: "knowledge" }); setSearchOpen(false); }}><BookOpen className="size-4" /><span>{article.title}</span></CommandItem>)}</CommandGroup></CommandList></CommandDialog>
    <Sheet open={notificationsOpen} onOpenChange={setNotificationsOpen}><SheetContent><SheetHeader><SheetTitle>SLA alerts · demo</SheetTitle><SheetDescription>Sample ticket alerts based on the current session. No email or push notification is sent.</SheetDescription></SheetHeader><div className="mt-6 divide-y border-y">{riskTickets.length ? riskTickets.map(ticket => <button key={ticket.id} onClick={() => { setNotificationsOpen(false); openTicket(ticket); }} className="flex w-full gap-3 py-4 text-left hover:bg-muted/40"><span className={`mt-2 size-2 shrink-0 rounded-full ${notificationsRead ? "bg-transparent" : "bg-amber-500"}`} /><div><p className="text-sm font-medium">SLA approaching · {ticket.id}</p><p className="text-sm text-muted-foreground">{ticket.title} · {ticket.sla} remaining</p></div></button>) : <p className="py-5 text-sm text-muted-foreground">No tickets are currently at risk in the demo.</p>}</div><Button variant="outline" className="mt-4 w-full" onClick={() => { setNotificationsRead(true); toast.success("Demo alerts marked as read"); }}>Mark all as read</Button></SheetContent></Sheet>
    <CreateTicket open={createOpen} onClose={() => { setCreateOpen(false); setSeedAssetId(undefined); }} onSubmit={createTicket} onView={id => navigate({ page: "ticket", id })} seedAssetId={seedAssetId} /><Toaster richColors position="bottom-right" />
  </SidebarProvider>;
}
